### ISSUE TITLE
«Wrong file» on opening any frontend product page in Windows

### ISSUE THREAD

**Issue by dmitry-fedyuk** [dxmoto/site#26]
![01](https://user-images.githubusercontent.com/83204/89115050-35787300-d4a5-11ea-8dc9-b234704f10fa.png)

**Comment by dmitry-fedyuk** [comment]
It is an image is passed to `\Magento\Framework\Image\Adapter\Gd2::validateURLScheme()` as a filesystem path (e.g. `C:/work/clients/dxmoto.com/m/2020-07-10/235/code/pub/media/catalog/product//3/4/34300006-tech-8-dual-compound-sole-with-replaceable-insert-b.jpg`) instead of an URL

**Comment by dmitry-fedyuk** [comment]
https://github.com/magento/magento2/issues/28055#issuecomment-622533641

**Comment by dmitrii-fediuk** [comment]
[How to fix product images in Magento 2.3.5 in Windows?](https://mage2.pro/t/6210)
