### ISSUE TITLE
«"var/log/advancedstock_inventory_core.log" cannot be opened with mode "a"»

### ISSUE THREAD

**Issue by dmitry-fedyuk** [dxmoto/site#45]
![01](https://user-images.githubusercontent.com/83204/92416434-480a5a00-f17f-11ea-86a5-162c0978527b.png)

**Comment by dmitry-fedyuk** [comment]
Solved by
```shell
bin/magento cache:clean
```

**Comment by dmitrii-fediuk** [comment]
The true solution seems to be https://github.com/canadasatellite-ca/site/commit/9a340e86
